### PR TITLE
bump go-libp2p version to v0.17.0 to add hole punching support

### PR DESCRIPTION
**Pull request by optman**
mdns compiled but not works, no idea why.

### CODE REVIEW

**Comment by dennis-tra** [comment]
Awesome! Thanks a lot for the PR! Not sure if you read it, but this comes right in time as we were just discussing this in #18!

Unfortunately, I will only have time to take a look at it next week, but this will most likely land in here :)

**Comment by optman** [comment]
Good to known that. And then you could check the mdns issue also  :)

**Comment by decentral1se** [comment]
Amazing! Was just wondering if `pcp` would be supporting the new hole punching work. Super cool.

**Comment by dennis-tra** [comment]
@optman I filed a PR against your PR with a fix for the mDNS discovery. However, the decentralized hole punching documentation suggests a more involved connection handling than currently implemented. I have the chance to chat with some libp2p devs in a couple of weeks and will bring that up then.

**Comment by megapro17** [comment]
can you upload compiled windows binary?

**Comment by dennis-tra** [comment]
Feel free to keep this PR open. Just yesterday I had the chance to catch up with some of the devs and he mentioned the missing option:
```
libp2p.EnableAutoRelay(autorelay.WithDefaultStaticRelays()),
```

I'll test this branch with the above additional option and would leave feedback here or make changes right away.

**Comment by optman** [comment]
I just notice the PR is on based on the wrong branch, it contains many unrelated commits. Anyway, you have merged the code on distributed-hole-punching branch. 

I don't think `WithDefaultStaticRelays` would be any help, it is only there to quicken relay establish.

https://github.com/libp2p/go-libp2p/blob/f0db9cc407a2982faa5a04563ad5fc48326932ce/p2p/host/autorelay/autorelay.go#L173

**Pull request closed without merging**
